# Generated by Django 5.1.4 on 2025-01-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
